[build]
  publish = "client/dist"
  command = "cd client && npm install && npm run build && cd ../netlify/functions && npm install && npx prisma generate"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  included_files = ["netlify/functions/prisma/**"]

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/tasks/*"
  to = "/.netlify/functions/tasks/:splat"
  status = 200

[[redirects]]
  from = "/api/tasks"
  to = "/.netlify/functions/tasks"
  status = 200

[[redirects]]
  from = "/api/screenshots/*"
  to = "/.netlify/functions/screenshots/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
